version: "3.8"

services:
  # Nginx 反向代理服务
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: vps_nginx
    restart: unless-stopped
    ports:
      - "13344:80"                                           # 暴露端口 13344
    depends_on:
      - frontend
    networks:
      - vps_network
    volumes:
      - ./nginx/logs:/var/log/nginx                         # 日志持久化
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # 前端服务 (Nuxt.js with Nitro)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: vps_frontend
    restart: unless-stopped
    environment:
      # Nuxt public runtime config
      NUXT_PUBLIC_API_BASE: ${NUXT_PUBLIC_API_BASE:-http://localhost:3000}
      NUXT_PUBLIC_SITE_NAME: ${SITE_NAME:-VPS Deals}
      NUXT_PUBLIC_SITE_URL: ${SITE_URL:-https://your-domain.com}
      NUXT_PUBLIC_SITE_DESCRIPTION: ${SITE_DESCRIPTION:-发现最优惠的VPS主机方案}
      
      # Server runtime config
      NITRO_PORT: 3000
      NITRO_HOST: 0.0.0.0
      NODE_ENV: ${NODE_ENV:-production}
      
      # 数据库配置
      DB_HOST: ${DB_HOST:-localhost}
      DB_PORT: ${DB_PORT:-3306}
      DB_USER: ${DB_USER:-vps_user}
      DB_PASSWORD: ${DB_PASSWORD:-your_db_password}
      DB_DATABASE: ${DB_DATABASE:-vps_deals}
      
      # JWT配置
      JWT_SECRET: ${JWT_SECRET:-yoursecretkeyforsupersecuritychangeit}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      
      # 管理员配置
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-your_admin_password}
      
      # Redis配置
      REDIS_HOST: ${REDIS_HOST:-}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      REDIS_DB: ${REDIS_DB:-0}
    volumes:
      - ./uploads:/app/uploads                               # 上传文件目录
    networks:
      - vps_network
      - 1panel-network

# 网络定义
networks:
  vps_network:
    driver: bridge
  1panel-network:
    external: true